name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install
        
      - name: Cypress run
        run: npx cypress run